foodbank/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    #path('app/', include('foodbank.urls', namespace='app')),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login_view,name='login'),
    path('donate/',views.food_donation_form,name='donation'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('donate/donate/',views.donatesuccess,name='donatesuccess'),
    path('donate/donate/homepage',views.home,name='home'),
    path('order/',views.order_page,name='order'),
    path('post/',views.food_items,name='items'),
    path('deliverlogin',views.delivery,name='delivery'),
    path('dashboard/',views.dashboard,name='dashborad'),
    path('accept_order/', views.accept_order, name='accept_order'),
    path('login/signup',views.signup,name='signup')
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    USERTYPE_CHOICES = [
        ('volunteer', 'Volunteer'),
        ('ngo', 'NGO'),
        ('donor', 'Donor'),
    ]
    usertype = models.CharField(
        max_length=10,
        choices=USERTYPE_CHOICES,
        default='donor'
    )

class FoodDonation(models.Model):
    foodname = models.CharField(max_length=100)
    email = models.EmailField()
    phoneno = models.CharField(max_length=15)
    is_veg = models.BooleanField(default=False)
    is_nonveg = models.BooleanField(default=False)
    quantity = models.PositiveIntegerField()
    address = models.TextField()
    donation_date = models.DateField(default=timezone.now)  # Date field for donation date
    donation_time = models.TimeField(default=timezone.now)

    def __str__(self):
        return self.foodname

class Order(models.Model):
    customer = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    food_donation = models.ForeignKey(FoodDonation, on_delete=models.CASCADE)  # Add this line
    product = models.CharField(max_length=100)
    quantity = models.PositiveIntegerField()
    place = models.CharField(max_length=1000, default="Erode")
    
class FoodItem(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    quantity = models.IntegerField()

app/forms.py
from django import forms
from .models import User,FoodDonation,Order
from django.contrib.auth.forms import AuthenticationForm


class SignupForm(forms.ModelForm):
    USERTYPE_CHOICES = [
        ('volunteer', 'Volunteer'),
        ('ngo', 'NGO'),
        ('donor', 'Donor'),
    ]
    
    usertype = forms.ChoiceField(
        choices=USERTYPE_CHOICES,
        required=True,
        widget=forms.Select(attrs={'class': 'custom-select'}),
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'usertype']
        widgets = {'password': forms.PasswordInput()}
        
class Loginform(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'your-custom-class'})
        self.fields['password'].widget=forms.PasswordInput()

class FoodDonationForm(forms.ModelForm):
    class Meta:
        model = FoodDonation
        fields = '__all__'  

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['product', 'quantity', 'place'] 

app/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login
from .forms import SignupForm,FoodDonationForm,OrderForm,Loginform
from django.contrib.auth.models import User,auth
from django.shortcuts import redirect
from django.contrib import auth
from django.contrib import messages
from .models import FoodDonation,FoodItem,Order

# Create your views here.
def signup(request):
    if request.method == 'POST':
        username=request.POST['username']
        email=request.POST['email']
        password=request.POST['password']
        #form = SignupForm(request.POST)
        #if form.is_valid():
           # form.save()
        user=User(username=username,password=password,email=email)
        user.save()
        return redirect('login')  # Redirect to login page after successful signup
    else:
        form = SignupForm()

    return render(request, 'signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form=Loginform(request.POST)
        if form.is_valid():
            username=form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request,username=username,password =password)
            if user is not None:
                login(request,user)
                try:
                    user_profile = UserProfile.objects.get(user=user)
                    user_type = user_profile.usertype
                    if user_type == 'volunteer':
                        return redirect('deliverlogin/')
                    elif user_type == 'ngo':
                        return redirect('post/')  
                    elif user_type == 'donor':

                        return redirect('donate') 
                    else:
                        messages.error(request, 'Invalid user type')
                except UserProfile.DoesNotExist:
                    messages.error(request, 'User profile not found')
            else:
                messages.error(request, 'Invalid username or password')
        else:
            messages.error(request, 'Credentials Invalid')
    else:
        form = Loginform()
    return render(request, 'login.html', {'form': form})
def food_donation_form(request):
    if request.method == 'POST':
        form = FoodDonationForm(request.POST)
        if form.is_valid():
            foodname=request.POST['foodname']
            email=request.POST['email']
            phoneno=request.POST['phoneno']
            quantity=request.POST['quantity']
            address=request.POST['address']
            form.save()
            return redirect('donate/')  # Redirect to a thank-you page or another page
    else:
        form = FoodDonationForm()

    return render(request, 'donate.html', {'form': form})

def home(request):
    return render(request,'homepage.html')

def dashboard(request):
    # Fetch relevant data for the dashboard
    total_donations = FoodDonation.objects.count()
    total_food_items = FoodItem.objects.count()
    total_users = User.objects.count() 
    food_items = FoodDonation.objects.all()
    context = {
        'total_donations': total_donations,
        'total_food_items': total_food_items,
        'total_users':total_users,
        'food_items':food_items,

        #'total_volunteers': total_volunteers,
    }

    return render(request, 'dashboard.html', context)

def post(request):
    return render(request,'post.html')

def order_page(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.customer = request.user  # Assign the current user as the customer
            order.save()
            return redirect('order.html')
              # Redirect to a success page after order submission
    else:
        form = OrderForm()

    return render(request, 'order.html', {'form': form})

def donatesuccess(request):
    return render(request,'donatesuccess.html')

def food_items(request):
    
    food_items = FoodDonation.objects.all()
    return render(request, 'post.html', {'food_items': food_items})

def delivery(request):
    food_items = FoodDonation.objects.all()
    all_orders = Order.objects.all()
    return render(request, 'deliverlogin.html', {'all_orders': all_orders, 'food_items': food_items})

def accept_order(request):
    return render(request,'accept_order.html')

app/templates/accept_order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> 
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>

    
    <link rel="stylesheet" href="navbar.css">
    <style>
        body{
    background-image: white;}
    .table {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  text-align: left;
  font-family: arial;
  font-size: 15px;
  background: rgb(245, 241, 241);
  margin-left: 2px;
  border-radius: 5px;
  margin-bottom: 5px;
  width: 95%;
  gap: 2px;
}
.color-me{
    color:black !important;
    font-weight: bold !important;
    text-align: center !important;
}
.price{
    color: black;
    font-size:15px;
}
.table th {
  color: black !important;
  font-weight: bold !important;
}
.table button {
  border: none;
  outline: 0;
  padding: 12px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 60%;
  font-size: 10px;
  border-radius: 20px;
}

.table button:hover {
  opacity: 0.7;
}
    </style>
</head>
<body style="font-family:  'Poppins', sans-serif;">
    <nav class="navbar navbar-custom navbar-fixed-top">
        <div class="container-fluid" >
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"><span style="font-family:sans-serif;color:black;font-size: 25px;font-weight: 700;">Food</span><span style="font-family:sans-serif;color:#800080;font-size: 25px;font-weight: 700;">Bank</span></a>
            </div>
        <div class="navbar-right">
            <div class="collapse navbar-collapse" id="mynav">
                <ul class="nav navbar-nav">
                    <li  class="nav-item" ><a class="color-me" class="nav-link-active" href="homepage.html">HOME</a></li>
                    <li ><a class="color-me" href="#about" >ABOUT</a></li>
                    <li ><a class="color-me" href="#contact">CONTACT</a></li>
                    <li ><a class="color-me" href="login"><img src="{% static 'images/login (1).png' %}" width="30px" height="28px" style="align-items: center;"></a></li>
               </div>
        </div>
    </div>
</nav>
<h3 style="margin-top:80px;text-align:center">Current Location</h3>
<div id="map" style="width: 90%; height: 300px;margin-top: 20px;margin-left: 70px;"></div>
    <script>
        var map;
        var userMarker;

        // Initialize the map
        function initializeMap(userLat, userLng) {
            map = L.map("map").setView([userLat, userLng], 13);

            L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
                maxZoom: 19,
            }).addTo(map);

            // Create a marker at the user's location
            userMarker = L.marker([userLat, userLng]).addTo(map);
            userMarker.bindPopup("You are here!").openPopup();
        }

        // Get the user's current location
        function getUserLocation() {
            if ("geolocation" in navigator) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    var userLat = position.coords.latitude;
                    var userLng = position.coords.longitude;

                    // Initialize the map with the user's current location
                    initializeMap(userLat, userLng);
                });
            }
        }

        // Call the function to get the user's location and initialize the map
        getUserLocation();
    </script>
</body>
</html>

app/templates/deliverlogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> 
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>    
    <link rel="stylesheet" href="navbar.css">
    <style>
        body{
    background-image: white;}
    table {
    
    border: 1px solid #ccc;
    border-collapse: collapse;
    margin: 0;
    padding: 0;
    width: 100%;
    table-layout: fixed;
  }
  
  table caption {
    font-size: 1.5em;
    margin: .5em 0 .75em;
  }
  
  table tr {
    background-color: var(--panel-color);
    /* background-color: #f8f8f8; */
    border: 1px solid #ddd;
    padding: .35em;
    color: var(--text-color);
  }
  
  table th,
  table td {
    padding: .625em;
    text-align: center;
  }
  
  table th {
    font-size: .85em;
    letter-spacing: .1em;
    text-transform: uppercase;
  }
.color-me{
    color:black !important;
    font-weight: bold !important;
    text-align: center !important;
}
.price{
    color: black;
    font-size:15px;
}
.table th {
  color: black !important;
  font-weight: bold !important;
}
.table button {
  border: none;
  outline: 0;
  padding: 12px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 60%;
  font-size: 10px;
  border-radius: 20px;
}

.table button:hover {
  opacity: 0.7;
}
    </style>
</head>
<body style="font-family:  'Poppins', sans-serif;">
    <nav class="navbar navbar-custom navbar-fixed-top">
        <div class="container-fluid" >
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"><span style="font-family:sans-serif;color:black;font-size: 25px;font-weight: 700;">Food</span><span style="font-family:sans-serif;color:#800080;font-size: 25px;font-weight: 700;">Bank</span></a>
            </div>
        <div class="navbar-right">
            <div class="collapse navbar-collapse" id="mynav">
                <ul class="nav navbar-nav">
                    <li  class="nav-item" ><a class="color-me" class="nav-link-active" href="homepage.html">HOME</a></li>
                    <li ><a class="color-me" href="#about" >ABOUT</a></li>
                    <li ><a class="color-me" href="#contact">CONTACT</a></li>
                    <li ><a class="color-me" href="login"><img src="{% static 'images/login (1).png' %}" width="30px" height="28px" style="align-items: center;"></a></li>
               </div>
        </div>
    </div>
</nav>
<table class="table" style="margin-top: 70px;margin-left:20px;">
    <thead style="text-align: center;">
        <tr>
            <th>Food Name</th>
            <th>Date</th>
            <th>Time</th>
            <th>PickUp Address</th>
        </tr>
    </thead>
    <tbody>
        {% for food_item in food_items %}
        <tr>
            <td><b>{{ food_item.foodname }}</b></td>
            <td>{{food_item.donation_date}}</td>
            <td>{{food_item.donation_time}}</td>
            <td>{{ food_item.address }}</td>
            <td>
                {% for order in food_item.order_set.all %}
                {{ order.place }}
                {% endfor %}
            </td>
            <td>
                <a href="accept_order"><button type="button" data-toggle="modal" data-target="#acceptModalLabel">ACCEPT ORDER</button></a>

            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>



<!-- Modal for Reject -->
<!--<div class="modal fade" id="rejectModal" tabindex="-1" role="dialog" aria-labelledby="rejectModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="rejectModalLabel">Reject Order</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                 Include your reject order form here
                <form method="get" action="">
                    {% csrf_token %}
                    Add form fields as needed 
                    <div class="form-group">
                        <label for="reject_option">Reject Option:</label>
                        <input type="text" class="form-control" id="reject_option" name="reject_option" required>
                    </div>
                     Add more form fields as needed 
                    <button type="submit" class="btn btn-danger">Reject</button>
                </form>
            </div>-->
        </div>
    </div>
</div>
  
</body>
</html>

app/templates/donate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'tstyle.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> 
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>   
</head>
<body style="font-family:  'Poppins', sans-serif;">
    <nav class="navbar navbar-custom navbar-fixed-top">
        <div class="container-fluid" >
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"><span style="font-family:sans-serif;color:black;font-size: 25px;font-weight: 700;">Food</span><span style="font-family:sans-serif;color:#800080;font-size: 25px;font-weight: 700;">Bank</span></a>
            </div>
        <div class="navbar-right">
            <div class="collapse navbar-collapse" id="mynav">
                <ul class="nav navbar-nav">
                    <li  class="nav-item" ><a class="color-me" class="nav-link-active" href="homepage.html">HOME</a></li>
                    <li ><a class="color-me" href="#about" >ABOUT</a></li>
                    <li ><a class="color-me" href="#contact">CONTACT</a></li>
                    <li ><a class="color-me" href="login"><img src="{% static 'images/login (1).png' %}" width="30px" height="28px" style="align-items: center;"></a></li>
               </div>
        </div>
    </div>
</nav>
<div class="container">
    <div class="formbox">
    <h3 style="text-align: center;"><span style="font-family:sans-serif;color:black;font-size: 25px;font-weight: 700;">Food</span><span style="font-family:sans-serif;color:#800080;font-size: 25px;font-weight: 700;">Bank</span></h3>
    <form method="post">
        {% csrf_token %}
       <input type="text" name="foodname" placeholder="Food Name"> 
       <input type="email" name="email" placeholder="Email">
       <input type="text" id="phoneno" name="phoneno" placeholder="Phone Number">
       <label>NGO name:</label>
       <select >
        <option>ASHWINI</option>
        <option>EKAM Foundation</option>
        <option>Akshaya Trust</option>
       </select>
       <div class="input">
       <label>Meal Type:</label> 
       <input type="checkbox" name="veg">
       <label>Veg</label>  
       <input type="checkbox" name="nonveg">
       <label>Non-Veg</label>
       </div>
       <input type="number" id="quantity" name="quantity" placeholder="Quantity per person">
       <input type="text" id="address" name="address" placeholder="Address">
       <!-- Date and Time Inputs -->
    <label for="donation_date">Donation Date:</label>
    <input type="date" name="donation_date">
    <label for="donation_time">Donation Time:</label>
    <input type="time" name="donation_time">
       <a href="donatesuccess.html"><button type="submit" name="submit" class="margin-top: 20px;margin-left: 590px;" class="btn btn-lg">Donate</button></a>
       

     </form>
     </div>
     
     
    
</body>
</html>

app/templates/donatesuccess.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'tstyle.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> 
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>  
    <style>
        .itm{
            background-color: white;
            display: grid;
        }
        .itm img{
            margin-left: auto;
            margin-right: auto;
        }
        p{
            text-align: center; font-size: 20PX;color: black; margin-top: 100px;font-weight: 600;
        }
    </style> 
</head>
<body style="font-family:  'Poppins', sans-serif;">
    <nav class="navbar navbar-custom navbar-fixed-top">
        <div class="container-fluid" >
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"><span style="font-family:sans-serif;color:black;font-size: 25px;font-weight: 700;">Food</span><span style="font-family:sans-serif;color:#800080;font-size: 25px;font-weight: 700;">Bank</span></a>
            </div>
        <div class="navbar-right">
            <div class="collapse navbar-collapse" id="mynav">
                <ul class="nav navbar-nav">
                    <li  class="nav-item" ><a class="color-me" class="nav-link-active" href="homepage.html">HOME</a></li>
                    <li ><a class="color-me" href="#about" >ABOUT</a></li>
                    <li ><a class="color-me" href="#contact">CONTACT</a></li>
                    <li ><a class="color-me" href="login"><img src="{% static 'images/login (1).png' %}" width="30px" height="28px" style="align-items: center;"></a></li>
               </div>
        </div>
    </div>
</nav>
<div class="itm" >

    <!-- <p class="heading">We will reach soon</p> -->
    <p>"Your donate will be immediately collected and sent to needy people "</p>
    <img src="{% static 'images/package.gif' %}" alt="" width="200" height="200"> 
  
<p style="margin: 2px;">Thanks for donating</p>
  <p style="text-align: center;font-size: 20px;margin-top: 10px;"><a href="homepage">Return to home page</a></p>
   
</div>
</body>
</html>

app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Document</title>
<link rel="stylesheet" href="{% static 'style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
<div class="container" id="container">
    <div class="form-container log-in-container">
        <h1 style="text-align: center;">Login</h1>
        <div class="social-container"  style="padding-left: 100px;">
            <a href="https://youtu.be/k_4W9WhoOjI?si=DtqAQxcR4J-V8G7v" class="social"><i class="fa fa-facebook fa-2x"></i></a>
            <a href="#" class="social"><i class="fab fa fa-twitter fa-2x"></i></a>
        </div>
        <div>
            <style>
              h5{
                  color: red;
              }
          </style>
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
          </div>
        <form method="post">
            {% csrf_token %}
            <!--<label for="username">Username:</label>-->
            <input type="text" name="username" placeholder="Username" required><br>
           <!-- <label for="password">Password:</label>-->
            <input type="password" name="password" placeholder="Password" required><br>
            <button type="submit">Login</button>
        <a href="signup" style="text-align: center;padding-top: 2px;"> Not Registered?Register Now</a><br>
        <a href="#" style="text-align: center;padding-top: 1px;margin-top: -10px;">Forget Password</a>
        </form>

    </div>
    <div class="overlay-container">
        <div class="overlay">
            <div class="overlay-panel overlay-right">
                <img src="{% static 'images/campaign-main.jpg'%}" width="140%" height="150%" >
                <h1>login to our page and Be the first to hands on special offers!</h1>
            </div>
        </div>
    </div>
</div>
</body>
</html>

app/templates/order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'tstyle.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> 
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script> 
    <style>
        .itm{
            background-color: white;
            display: grid;
        }
        .itm img{
            margin-left: auto;
            margin-right: auto;
        }
        p{
            text-align: center; font-size: 20PX;color: black; margin-top: 100px;font-weight: 600;
        }
    </style>   
</head>
<body style="font-family:  'Poppins', sans-serif;">
    <nav class="navbar navbar-custom navbar-fixed-top">
        <div class="container-fluid" >
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"><span style="font-family:sans-serif;color:black;font-size: 25px;font-weight: 700;">Food</span><span style="font-family:sans-serif;color:#800080;font-size: 25px;font-weight: 700;">Bank</span></a>
            </div>
        <div class="navbar-right">
            <div class="collapse navbar-collapse" id="mynav">
                <ul class="nav navbar-nav">
                    <li  class="nav-item" ><a class="color-me" class="nav-link-active" href="homepage.html">HOME</a></li>
                    <li ><a class="color-me" href="#about" >ABOUT</a></li>
                    <li ><a class="color-me" href="#contact">CONTACT</a></li>
                    <li ><a class="color-me" href="login"><img src="{% static 'images/login (1).png' %}" width="30px" height="28px" style="align-items: center;"></a></li>
               </div>
        </div>
    </div>
</nav>
<div class="itm" >

    <!-- <p class="heading">We will reach soon</p> -->
    <p>"Your order will be delivered in short time."</p>
    <img src="{% static 'images/checked (1).png' %}" alt="" width="300px" height="300px"> 
  
<p style="margin: 2px;">Order Placed</p>
  <p style="text-align: center;font-size: 20px;margin-top: 10px;"><a href="homepage">Return to home page</a></p>
   
</div>
     
     
    
</body>
</html>

app/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Document</title>
<link rel="stylesheet" href="{% static 'style.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
   
<div class="container" id="container">
<div class="form-container log-in-container">
<form method="post">
<h1>Signup</h1>
<div class="social-container">
<a href="https://youtu.be/k_4W9WhoOjI?si=DtqAQxcR4J-V8G7v" class="social"><i class="fa fa-facebook fa-2x"></i></a>
<a href="#" class="social"><i class="fab fa fa-twitter fa-2x"></i></a>
</div>
<span></span>
{% csrf_token %}
<input type="text" placeholder="Username" name="{{form.username.name}}" id="{{form.username.id_for_label}}" />
<input type="email" placeholder="Email" name="{{form.email.name}}" id="{{form.email.id_for_label}}"  />
<input type="password" placeholder="Password" name="{{form.password.name}}" id="{{form.password.id_for_label}}" />
<label for="user-type">Select User Type:</label>
            <select name="{{ form.usertype.name }}" id="{{ form.usertype.label_tag }}">
                <option value="volunteer">Volunteer</option>
                <option value="donar">Donar</option>
                <option value="ngo">NGO's</option>
            </select><br><br>
<button>Sign Up</button>

<a href="#">Already have account?Login Here</a>
</div>

<div class="overlay-container">
<div class="overlay">
<div class="overlay-panel overlay-right">
<img src="{% static 'images/campaign-main.jpg'%}" width="140%" height="100%" >
<!--<h1>login to our page and Be the first to hands on special offers!</h1>-->
</div>
</div>
</div>
</div>
</form>

</body>
</html>